default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOSTNAME'] %>
  database: <%= ENV['DATABASE_NAME'] %>

development:
  <<: *default

test:
  <<: *default
  database: rails-form-training_test

staging:
  <<: *default

production:
  <<: *default
